### ISSUE TITLE
Charge Shot Enhancements

### ISSUE THREAD

**Issue by JJChalupnik** [DamnedNForsaken/MMLX#106]
Need to implement the Charge Shot End Animation so that we really feel the overlapping animation after the gun releases its charge.

Would like to add additional  particles to the charge effect, like he is pulling it from the air around him almost. Something to make it feel more fun and powerful. Think Kamehameha wave or Spirit bomb from DBZ in the way he charges it.

Would like to have him get slid back physically after firing the shot. Literally like a foot back to suggest its power.

Need to reset the orientation of the player after he fires. Try this:
- Do a full charge shot on the Hanmuru Doll. Try and kill him with it.
- The lock-on is higher than Megaman's default angle of view. This causes him to "lock" his orientation at a slightly tilted angle. I'll post a still frame example next time it happens.

Lastly, Would like to consider an alteration for how the Charge shot functions:
What do you think of making the charge shot auto charge when the player holds down the R2 Trigger? So that "Square" button is not necessary. On release, it fires. We can put a hold on the "storing charge shot for later" bit unless its easy to implement. I just think this will yield a better feel/control scheme. What do you think?

**Comment by DamnedNForsaken** [comment]
Deprecating this ticket
