### ISSUE TITLE
Need Proper Menu SFX when player navigates with a Gamepad

### ISSUE THREAD

**Issue by JJChalupnik** [DamnedNForsaken/MMLX#120]
Currently when the player navigates through the menu screens (including the title screen) with a gamepad, there is no audio feedback or limited audio feedback. We need to add the appropriate sounds for each button press/axis press.

**Comment by DamnedNForsaken** [comment]
The main menu this is all fixed.
@JJChalupnik need a workflow/design update on the pause menu. That should be a separate issue IMO. Please sync up with me on the pause menu one day. Its my baby.
