### ISSUE TITLE
Proper Zenny Movement behavior

### ISSUE THREAD

**Issue by JJChalupnik** [DamnedNForsaken/MMLX#14]
Pretty low on priority, but I think its an important element of polish that we will need eventually. This will make the game feel a bit more fun and dynamic.... literally.

![zennyexplosion](https://user-images.githubusercontent.com/10458429/46934600-3361cd80-d00d-11e8-9348-6158677559f4.gif)

The zenny explosions should be bigger, and the refractors should rotate and flop around before coming to a stop in their respective floating position. The gif shows a perfect example of this behavior from MML2. That feel and look should be our goal as far as zenny movement goes.

**Comment by DamnedNForsaken** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[MMLX - 21] FIne tune zenny exploding](https://trello.com/c/IOBzvRfB/23-mmlx-21-fine-tune-zenny-exploding)

**Comment by DamnedNForsaken** [comment]
How cool is that ^. I linked this issue to the Trello card/User Story. Now we can properly track its progress!

**Comment by JJChalupnik** [comment]
Zenny behavior is much better than before. Its nice to see some rotation. Still needs some TLC though. The explosive radius seems too small, and the rotations could feel more natural. Also, should the rotations snap to their resting positions, or transition to them. Mostly I'm concerned with how they feel when they blow up. Ratchet and Clank is a good example to look at too, with all the bolts. Just generally needs to feel bigger and more fun.

**Comment by DamnedNForsaken** [comment]
@JJChalupnik we are good on this?

**Comment by DamnedNForsaken** [comment]
@kaliber64 you killed it on this Bravo! Closing this.
