### ISSUE TITLE
Playing sounds when collecting health cubes or zenny

### ISSUE THREAD

**Issue by JJChalupnik** [DamnedNForsaken/MMLX#15]
This one is a super easy fix, and I've already fixed it multiple times but can't get it pushed via git desktop because of the .gitattributes error i keep receiving. So for now you'll have to make the quick fix.

Basically, move your play sound 2d nodes to the end of your magnet bp, just after the array remove node. That way the sound only plays when Megaman has successfully picked up a zenny or health cube. It will get rid of the false positives where the sound plays but the zenny is trailing Megaman or hasn't been removed yet.  The sfx-getenergy sound is already in the project, so this is a super quick and easy thing to fix.

**Comment by DamnedNForsaken** [comment]
Is this fixed with the latest merge?
if so attach the "reference to an issue or pull request" the flag-star looking thing, and close this issue, if not then whats the status?

**Comment by DamnedNForsaken** [comment]
^ Scratch that last comment, these changes were nuked when i replaced the master branch :(

**Comment by DamnedNForsaken** [comment]
I believe that this can be closed, right? @JJChalupnik
