### ISSUE TITLE
Arm does not follow target, but buster plasma does.

### ISSUE THREAD

**Issue by JJChalupnik** [DamnedNForsaken/MMLX#154]
Wasn't sure if this was ever actually fixed in a prior build but as you'll see in the uploaded demo release (visible when fighting hanmuru doll for example),  you can see that megaman's arm does not aim at his target when firing. The plasma however will hit its designated target.

**Comment by DamnedNForsaken** [comment]
https://github.com/DamnedNForsaken/MMLX/pull/180
