### ISSUE TITLE
Death Animation delay

### ISSUE THREAD

**Issue by JJChalupnik** [DamnedNForsaken/MMLX#155]
On player death state, we need a delay to actually see the player fall down and "die". Currently the player will see a freeze frame on the moment of 0 HP and I'm not sure the text is there either. We also need to ensure that he falls down when Health <= 0. I think as it currently stands, he will likely just stand there if it isn't a knockdown hit.

**Comment by DamnedNForsaken** [comment]
https://github.com/DamnedNForsaken/MMLX/pull/172
