### ISSUE TITLE
No Bomb Damage to Player or Enemies

### ISSUE THREAD

**Issue by JJChalupnik** [DamnedNForsaken/MMLX#156]
Bombs fired by Zakobon do not hurt Megaman, and they also do not hurt themselves. Might be nice to make them give an automatic knockdown blow to megaman and do significant damage. But even better to allow them to get injured when megaman kicks it back to them.

**Comment by DamnedNForsaken** [comment]
https://github.com/DamnedNForsaken/MMLX/pull/172
fixes
Bombs affecting the Zakobon is an enhancement-separate ticket but also needs discussion.
