### ISSUE TITLE
Jump is still a tad sluggish

### ISSUE THREAD

**Issue by JJChalupnik** [DamnedNForsaken/MMLX#161]
I've noticed a few instances where a jump button press will cause Megaman to literially sink briefly before jumping in the air. Something still feels sluggish about the jump. Just like the buster firing. Its really critical for him to be able to jump almost instantaneously after pressing the button.

**Comment by JJChalupnik** [comment]
This feels better now... what do you think?

**Comment by DamnedNForsaken** [comment]
Yep i haven't had any big issues with this lately im going to close, we can make another issue if this is reported again.
