### ISSUE TITLE
Mirumijee Trap Issues

### ISSUE THREAD

**Issue by JJChalupnik** [DamnedNForsaken/MMLX#163]
I know we will be creating the collapsing bridge for this to work, but we need to make sure that once enemies are defeated, the trap is no longer functional. 

For example, if the player defeats enemies, but then presses the button, the trap enables, preventing megaman from leaving, but there are no more enemies to remove the trap.

Maybe for now we just find a way to put in very rudimentary logic for that room, since there is so much to be done with it. Such as we just populate the bottom with lots of snakes, and they are always there. Then just remove the trap altogether, and have the bridge animate down and destroy when megaman walks on it. (This should happen AFTER getting the treasure on the opposing side.)

Thoughts?

**Comment by DamnedNForsaken** [comment]
Love the ideas. Yep sounds good to me.

**Comment by JJChalupnik** [comment]
I think the elevator is busted on the latest build... as of 5/22/20

**Comment by DamnedNForsaken** [comment]
Elevator works now, closing this issue, have also added some debug text there as well. Further refinement can be done along with opening another ticket.
