### ISSUE TITLE
Orbit Camera Aim Offset Improvements

### ISSUE THREAD

**Issue by JJChalupnik** [DamnedNForsaken/MMLX#171]
Currently the "timer" fix for the orbiting of the camera only seems to work with a mouse.

I think we should possibly approach this problem differently. If the player is firing, then we keep him oriented correctly. If not, (and arm is down) And the camera passes that 180 degree line as it orbits Megaman, then face megaman forward.  We can add other things like idles, and auto look at functions in the future.  Thoughts?

**Comment by DamnedNForsaken** [comment]
This works with the gamepad too... it is set at 4 seconds... should i decrease it?
Lets discuss more, as I think it should be refined further.

**Comment by JJChalupnik** [comment]
After some playtesting I think he should transition from his giving aiming position to the idle front facing position within 1 sec or less. It should be pretty seamless. Also, we can get some head Aim Offsets going for his character so he can look at stuff automatically in game. That will make for a nice tweak. Like enemies, NPCs, Loot, focal points, etc...

**Comment by DamnedNForsaken** [comment]
Updated this to 1sec. Tell me if this feels good @JJChalupnik

**Comment by JJChalupnik** [comment]
Still not resolved.... Pasted from the review notes:

- The camera rotation issue may also be something we need to discuss over a call. It's not just the timer, its the fact that when the player moves the camera, and they are in front of megaman, he will automatically look in that direction. The look aim feature essentially needs to be disabled if the player has the camera in front of megaman. That's the only conceivable way I can think of allowing us to cycle idles. There might be a better solution out there for this particular problem. Maybe we are thinking about it wrong or too hard.... Just play any 3rd person shooter and see how you can orbit the character and watch their idles. That's what I'm aiming for.

In thinking about this further, We may need to think about this a bit differently. Maybe Megaman holds idle until the player fires, then we keep aim on the players camera direction for a delay, and return back to idle if the player doesn't fire anymore. (After a different delay timer)
It just doesn't feel/ look right yet. Just about every 3rd person game does this well. We should be able to hit it. Thoughts?

**Comment by JJChalupnik** [comment]
Fixed! Much better now. Might need to revisit this behavior as it pertains to firing, but it's in a great spot now.
