### ISSUE TITLE
Megaman can accept player input during knockdown

### ISSUE THREAD

**Issue by JJChalupnik** [DamnedNForsaken/MMLX#174]
under certain conditions, Megaman can still receive input while in a knockdown animation state. Causing the player to slide him around while he slides on the ground. Kind of a weird bug to discover, but it has happened to me more than once or twice while testing.

**Comment by DamnedNForsaken** [comment]
This should be fixed now! Stateful issues were a huge problem before the last few commits to master.
We are aware of this issue now going forwards, and will continue to revisit the statefulness of megaman!
