### ISSUE TITLE
Kick does not do damage.

### ISSUE THREAD

**Issue by JJChalupnik** [DamnedNForsaken/MMLX#33]
Maybe it happened during migration, but the kicks no longer do damage and/or fire off sounds when hitting a target.

**Comment by DamnedNForsaken** [comment]
Should the kicks to damage? They didn't in the original did they?
Im not advocating that they should or not, as all this is easy enough to implement.

**Comment by DamnedNForsaken** [comment]
@JJChalupnik this is fixed right? I have to double check and will close if this is the case.

**Comment by DamnedNForsaken** [comment]
This is fixed now, see https://github.com/DamnedNForsaken/MMLX/pull/55
