### ISSUE TITLE
Mirumjee Snakes not deploying or dying

### ISSUE THREAD

**Issue by JJChalupnik** [DamnedNForsaken/MMLX#34]
another migration problem is the enemy trap with the snake Mirumjees. 

They no longer deploy down, and it appears they also don't die, so once you are in the trap you are stuck there forevs.

**Comment by DamnedNForsaken** [comment]
Yeah i saw this last night too lol.. Was looking into it, there was some migration problem.

**Comment by DamnedNForsaken** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[MMLX - 56 ] HOTFIX - snakes](https://trello.com/c/6OIlZH3t/56-mmlx-56-hotfix-snakes)

**Comment by DamnedNForsaken** [comment]
https://github.com/DamnedNForsaken/MMLX/pull/67
