### ISSUE TITLE
Level Streaming Polish

### ISSUE THREAD

**Issue by JJChalupnik** [DamnedNForsaken/MMLX#35]
Need better level streaming. My goal is for the flow of events to looks like this:

1.) Show UE4 Logo and Maybe our Respective logos. 

2.) Start menu opens on a vista shot of the tower in the distance, complete with an ocean view, clouds, birds, atmosphere and sound design. The prologue text is also visible and possibly truncated for brevity.

3.) On the above stated start menu will be Start Game, Options, and Quit. When the player presses start game, the iconic "Here We Go!" Will play. This will trigger an event that will fade out the text on the start screen, and play an animation of the Flutter, flying past the camera and heading to the tower. We then fade to black and fade in on the opening sequence of Megaman in the refractor room.

4.) After the cutscene, once outside the refractor room, we play through the demo, complete with updated art, code, and gameplay to capture a modern sense of legends.

5.) On approaching the Hanmuru doll at the end of the level, we defeat the first round, initiate a cutscene that will load the exterior, and fight a second round on the roof. (This is a variation from the original) When it seems like megaman can't win, (Something we will have to enforce) He escapes via the Flutter and flies away.

6.) Fade out with a thank you message to all the gamers who supported the project, and maybe a final message showing a short url where to download assets to make their own legends.

All the streaming needs to feel seamless, with no actual load screens. (Fade in and Fade outs like the original are ok) I'm down to create diagnostics for us in the meantime if necessary(Like loading percentages), but my gut says hopefully we won't need to since the game really isn't that big. (yet)

**Comment by DamnedNForsaken** [comment]
Deprecating this ticket
