### ISSUE TITLE
Charge Shot Issues

### ISSUE THREAD

**Issue by JJChalupnik** [DamnedNForsaken/MMLX#58]
Here are list of issues with the Charge Shot:
- [x] If you jump and then press the charge pose, Megaman will stutter/levitate/float, need to fix this somehow.

- [x] Charge shot still follows camera position. Needs to lock in vector when player gets in charge pose, so that the blast always fires in the correct direction/vector

- [ ] Need to be able to hold a charge to fire at a later time. Think Samus from Super Smash Bros. The next time the player fires, it shoots the big one, triggering the charge shot firing animation

**Comment by DamnedNForsaken** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[MMLX-54] Charge Shot Issues](https://trello.com/c/mG2l4UAw/54-mmlx-54-charge-shot-issues)

**Comment by DamnedNForsaken** [comment]
Need to be able to hold a charge to fire at a later time. Think Samus from Super Smash Bros. The next time the player fires, it shoots the big one, triggering the charge shot firing animation

Hell yea that is the idea!! Also just like Megaman X...

**Comment by DamnedNForsaken** [comment]
So barely saw all this as their was no action mapping to the keyboard... which i have only been testing with lately. Now mapped to "y" key

**Comment by DamnedNForsaken** [comment]
If you jump and then press the charge pose, Megaman will stutter/levitate/float, need to fix this somehow
This is fixed

**Comment by DamnedNForsaken** [comment]
I think with:
https://github.com/DamnedNForsaken/MMLX/pull/92
I am going to close this
