### ISSUE TITLE
Buster Gun and Kick improvements

### ISSUE THREAD

**Issue by JJChalupnik** [DamnedNForsaken/MMLX#59]
Some of the reaverbots and objects dont have the same reaction sound fx when damage is given, as well as the particle fx when it receives damage from an attack. It would be nice to set up the logic so all objects share that consistent feel:
- [x] Flash when damage taken
- [ ] Impact fx from buster plasma to enemy/prop
- [ ] Sound fx of damage taken and sound fx of destroyed
- [ ] Larger explosion fx when enemy is destroyed.

**Comment by DamnedNForsaken** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[MMLX-48] Buster gun and kick improvements](https://trello.com/c/3UVz3aGZ/53-mmlx-48-buster-gun-and-kick-improvements)

**Comment by DamnedNForsaken** [comment]
Ah I will fix this, i have added a card to trello code board to relate to this ticket.

**Comment by ReishiRamzi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[MMLX - 77] Reaverbot Parent Class Interactions](https://trello.com/c/TF25Y5Zq/64-mmlx-77-reaverbot-parent-class-interactions)

**Comment by DamnedNForsaken** [comment]
I feel like we can deprecated this now. Once 77 is done.

**Comment by DamnedNForsaken** [comment]
I retract my last comment, and have added milestones now, so that we can properly track the order in which this issues should be addressed.

**Comment by DamnedNForsaken** [comment]
WIP, and aware of this as we iterate. deprecating this ticket
