### ISSUE TITLE
Hanmuru Doll Orientation offset

### ISSUE THREAD

**Issue by JJChalupnik** [DamnedNForsaken/MMLX#60]
This is a pretty simple one but I thought I'd mark it here to make sure it gets done for our next build. Basically the perception and rotation of the Hanmuru doll appears to be offset by about 90 degrees. Should hopefully be a relatively simple fix. When Megaman is detected, the Hanmuru doll chases him by gliding sideways.

**Comment by DamnedNForsaken** [comment]
Oh yea :p this is my bad i have assigned this to me, and will just throw it into another branch (bad practice but such a quick fix)

**Comment by DamnedNForsaken** [comment]
This was fixed with:
https://github.com/DamnedNForsaken/MMLX/pull/63
closing issue
