### ISSUE TITLE
Need a new mesh for the Ocean Exterior plane.

### ISSUE THREAD

**Issue by JJChalupnik** [DamnedNForsaken/MMLX#61]
Need a new mesh for the Ocean Exterior plane. Something that accepts the blueprint for the ocean shader, and will allow for the tessellated displacement, but also have a hole for Megaman and the elevator to not visibly collide through as he travels to the surface. This is more of an Art note. I'll make a trello board.

**Comment by DamnedNForsaken** [comment]
Yes I am closing this, because this is not an issue :|
