### ISSUE TITLE
Reaverbot Parent Class Interactions

### ISSUE THREAD

**Issue by ReishiRamzi** [DamnedNForsaken/MMLX#77]
This issue aims to consolidate other issues relating to interactions with reaverbots that can be solved with an improved reaverbot base class. 

- [x] behavior tree implementation
- [x] flash when damage taken
- [x] sfx on damage taken
- [x] parent class
- [x] configurable child class

**Comment by ReishiRamzi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[MMLX - 77] Reaverbot Parent Class Interactions](https://trello.com/c/TF25Y5Zq/64-mmlx-77-reaverbot-parent-class-interactions)

**Comment by DamnedNForsaken** [comment]
Please remove the following:
[MMLX - 23] Add Hanmuru Doll logic and basic attacks.
[MMLX - 24] Add spider movement, and bomb drops
as this issue/work will not be affecting all of the children.

**Comment by DamnedNForsaken** [comment]
Partially completed by Reish! Deprecating this ticket
