### ISSUE TITLE
kick makes controls unresponsive

### ISSUE THREAD

**Issue by DamnedNForsaken** [DamnedNForsaken/MMLX#8]
Sometimes when you kick it makes the rest of the controls unresponsive.
(recreate-able) Happens all the time whenever you start the game, and then kick immediately

**Comment by JJChalupnik** [comment]
Yup. I see it too. Everything currently works better with a controller in hand. Keyboard controls need some serious love.

**Comment by DamnedNForsaken** [comment]
I still see this issue.
use case start moving (notice how you can move the player mesh towards the camera forwards vector), then kick, 
now notice that you can't rotate the player's mesh anymore - it is locked towards the capsaul forward vector.

I believe that this issue is not in the mega blueprint but with the animation blending itself?... i.e. it doesn't return to the init state when it is done... but IDK, more investigation needed.

**Comment by JJChalupnik** [comment]
Maybe fixed after that latest round.... Check and see. I'll close this until we discover a new bug with it.
