### ISSUE TITLE
Megaman Delayed Arm Drop (Silhouette) Issue

### ISSUE THREAD

**Issue by JJChalupnik** [DamnedNForsaken/MMLX#86]
The time delay should be dependent on the last time the buster gun was fired, not the movement of the orbit camera. 

Also, we still need to add the firing while idle animation to round it out. To make it feel snappy, we clip the anim and play it about one frame before firing the actual plasma. In other words:
The player hits X on the gamepad, animation triggers right before plasma leaves the gun, then the overlapping animation continues through to "suggest" the full anim

I also experienced a random bug where I was no longer able to fire after being "knocked down" repeatedly. It was a strange issue.  These were the main things I noticed. The behavior looks awesome!!!

**Comment by DamnedNForsaken** [comment]
https://github.com/DamnedNForsaken/MMLX/pull/89
https://github.com/DamnedNForsaken/MMLX/pull/84
