### ISSUE TITLE
Zenny Feedback

### ISSUE THREAD

**Issue by JJChalupnik** [DamnedNForsaken/MMLX#9]
Zenny looks and operates much better now. For this module to feel complete, here are some fixes I'd like to address:
- Zenny should "explode" out from enemies. Rotating in the air like debris, before their final resting state with them rotating just above the ground.
- Zenny sound should occur not on player capsule overlap, but when the refractor hits the players location. This will stop any false positives as he collects them, and will ensure any stragglers hit with the sound as appropriate.
- Zenny should explode with an array of other zenny types, including a health cube. Each type should occur based a probability, to keep things fresh feeling and unique.
- Eventually we'll swap each model out with the appropriate model type, and then tweak adjustments as necessary.

**Comment by DamnedNForsaken** [comment]
- [x] Zenny explode out correctly
- [x] I believe that this works well enough at the moment if not we can revist
- [x] This functionality is now in place. We do need to fine tune this and have created a card on the trello board for this.
- [x] Agreed and cool. Have created a card for this as well.
