### ISSUE TITLE
Standing Idle BusterGun Firing Improvements

### ISSUE THREAD

**Issue by JJChalupnik** [DamnedNForsaken/MMLX#90]
Stand and Fire animation needs some improved implementation.

Currently, it fires the animation once, and then repeats, either when the player continues to tap the fire button, or hold down the fire button. We need to implement the functionality of the original game, to make use of the Rapid and Energy Stats properly. 

The player should only be able to hold a shot if the Charge shot pose is active, or if the player has a full charge shot. so if they hold down the fire button, we should see him fire based on the Rapid and energy stats.

We'd loop this firing animation, and this animation's speed based off the Rapid Variable. Ensuring that every time a plasma blast exits Megaman's bustergun, the animation fires at the point in which he feels the recoil from the shot. This will ensure that it feels like every shot has weight behind it.

We also need to play the animation and cut off the animation at appropriate times. The current animation should be cut off when the player starts moving. If the player moves forward while firing in a standing pose, the player will slide in that pose, so we should definitely fix this.

Alternatively, if the player fires faster than the animation allows, we should stop the current playing animation, and start a new one at the point of recoil on the animation. That way again, every shot has weight and it makes logical sense. This should hopefully round out this feature.

**Comment by DamnedNForsaken** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[MMLX-79] Idle shot tuning.](https://trello.com/c/4Vcx7Ufu/69-mmlx-79-idle-shot-tuning)

**Comment by DamnedNForsaken** [comment]
https://github.com/DamnedNForsaken/MMLX/pull/92
