### ISSUE TITLE
Interact with Treasure Chest Requires player to hold 'interact' as they begin overlap on Trigger Volume

### ISSUE THREAD

**Issue by JJChalupnik** [DamnedNForsaken/MMLX#91]
There's a bug with the interaction between the Treasure Chest and the player that is left over from the Walk cycle development. We need to make it so Megaman can trigger the treasure chest once he is inside the volume. Currently the player can only open the chests if they hold the interact button as the approach the volume. If they are already inside and press interact Nothing happens. At least on the build I've been looking at, which should be 'master'. 

Should hopefully be an easy fix, but It hasn't been addressed yet so I figured I'd mention it here.

**Comment by DamnedNForsaken** [comment]
https://github.com/DamnedNForsaken/MMLX/pull/92

**Comment by DamnedNForsaken** [comment]
Fixed
